# Generated by Django 4.1.6 on 2023-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrcode',
            fields=[
                ('qrcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('games_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studeny_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('games_completed', models.IntegerField(default=0)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
