# Generated by Django 4.1.5 on 2023-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrcode',
            fields=[
                ('qrcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('games_completed', models.IntegerField(default=0)),
            ],
        ),
    ]
