# Generated by Django 4.1.5 on 2023-02-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_qrcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qrcode',
            new_name='qrcodebdd',
        ),
    ]
