# Generated by Django 4.1.5 on 2023-02-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
