# Generated by Django 4.1.5 on 2023-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_student_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='validated',
            field=models.CharField(default="n'a pas validé", max_length=255),
        ),
    ]
