# Generated by Django 4.1.5 on 2023-02-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_student_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
